name: Build Ravn

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip source
        run: |
          unzip Ravn.zip -d source
          ls -la source

      - name: Find project
        run: |
          find source -maxdepth 3 -name gradlew -o -name build.gradle

      - name: Make Gradle executable
        run: |
          chmod +x source/gradlew

      - name: Build
        run: |
          cd source
          ./gradlew build

      - name: Upload compiled JAR
        uses: actions/upload-artifact@v4
        with:
          name: Ravn-build
          path: source/build/libs/*.jar
